# Generated by Django 3.1.7 on 2022-06-03 11:18

from django.db import migrations, models
import english.validators


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='video_content',
            field=models.FileField(null=True, upload_to='video/', validators=[english.validators.validate_is_video]),
        ),
    ]
