# Generated by Django 3.1.7 on 2022-06-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_auto_20220603_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='english.quiz'),
        ),
    ]
