# Generated by Django 4.0.5 on 2022-06-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0005_alter_answer_id_alter_choice_id_alter_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_lesson',
            field=models.IntegerField(default=1),
        ),
    ]
