# Generated by Django 4.0.5 on 2022-06-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0006_student_current_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
